### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by travis-r6s** [dturton/gridsome-shopify-source#1]
Hello,

I've also recently been working on a shopify source package - https://github.com/thetre97/gridsome-source-shopify - but when I came to publish it, it appears someone else had already had the same idea :)

Do you intend to continue working on this, or would you consider transferring the package name?

Thanks,

Travis

**Comment by travis-r6s** [comment]
@dturton Just wondering if you have had a chance to look at this?

**Comment by dturton** [comment]
Hi @thetre97 I haven't had time to work on lately. I could gladly transfer the package name. Do you know how I would do that?

**Comment by travis-r6s** [comment]
That's, great, thanks. I believe you can add me as a maintainer on the npm package admin page - https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account. If it needs an email address, please use travis@cirruscreative.co.uk.


Thanks,


Travis

**Comment by dturton** [comment]
I need your npm username .

**Comment by travis-r6s** [comment]
Ah, sorry - that is `travisreynolds`.

**Comment by dturton** [comment]
done.. can you keep me posted on your progress? I am also interested in building static sites with Shopify.

**Comment by travis-r6s** [comment]
Thank you. Of course - I have been putting a bit on the gridsome discord recently, including a starter using the shopify source plugin:

https://gridsome-shopify-starter.netlify.com
https://github.com/thetre97/gridsome-starter-shopify
